package com.dev.baseproject.utils

import com.dev.baseproject.BuildConfig

object Constants {
    const val TIME_DELAY_SPLASH_MAX = 9000L

    const val KEY_ANALYTICS_TRACKING = "KEY_ANALYTICS_TRACKING"
    const val VALUE_ANALYTICS_TRACKING = "tracking_flow"

    const val URL_POLICY = "https://sites.google.com/view/higherstusioclaptofindphone"
    const val EMAIL = "khanhhigher@gmail.com"
    const val SUBJECT_EMAIL = "Feedback Find Phone By Clap, Voice - " + BuildConfig.VERSION_NAME
    const val BUNDLE_ANALYTICS_GO_TO_SETTING_LANGUAGE_FIRST = "GO_TO_SETTING_LANGUAGE_FIRST"
    const val BUNDLE_ANALYTICS_GO_TO_SETTING_LANGUAGE_AGAIN = "GO_TO_SETTING_LANGUAGE_AGAIN"

    const val BUNDLE_ANALYTICS_GO_TO_SPLASH_FIRST = "GO_TO_SPLASH_FIRST"
    const val BUNDLE_ANALYTICS_GO_TO_INTRO_2_FIRST = "GO_TO_INTRO_2_FIRST"
    const val BUNDLE_ANALYTICS_GO_TO_INTRO_2_AGAIN = "GO_TO_INTRO_2_AGAIN"
    const val BUNDLE_ANALYTICS_GO_TO_INTRO_3_FIRST = "GO_TO_INTRO_3_FIRST"
    const val BUNDLE_ANALYTICS_GO_TO_INTRO_3_AGAIN = "GO_TO_INTRO_3_AGAIN"
    const val BUNDLE_ANALYTICS_GO_TO_LANGUAGE_FIRST = "GO_TO_LANGUAGE_FIRST"
    const val BUNDLE_ANALYTICS_GO_TO_LANGUAGE_AGAIN = "GO_TO_LANGUAGE_AGAIN"
    const val BUNDLE_ANALYTICS_GO_TO_SPLASH = "GO_TO_SPLASH"
    const val BUNDLE_ANALYTICS_LANGUAGE_ENLISH = "LANGUAGE_ENLISH"
    const val BUNDLE_ANALYTICS_LANGUAGE_VIETNAM = "LANGUAGE_VIETNAM"
    const val BUNDLE_ANALYTICS_LANGUAGE_HINDI = "LANGUAGE_HINDI"
    const val BUNDLE_ANALYTICS_LANGUAGE_JAPAN = "LANGUAGE_JAPAN"
    const val BUNDLE_ANALYTICS_LANGUAGE_KOREA = "LANGUAGE_KOREA"
    const val BUNDLE_ANALYTICS_LANGUAGE_CHINA = "LANGUAGE_CHINA"
    const val BUNDLE_ANALYTICS_LANGUAGE_PORTUGUESE = "LANGUAGE_PORTUGUESE"
    const val BUNDLE_ANALYTICS_LANGUAGE_SPANISH = "LANGUAGE_SPANISH"
    const val BUNDLE_ANALYTICS_LANGUAGE_GERMAN = "LANGUAGE_GERMAN"
    const val BUNDLE_ANALYTICS_LANGUAGE_RUSSIAN = "LANGUAGE_RUSSIAN"
    const val BUNDLE_ANALYTICS_LANGUAGE_UKRAIAN = "LANGUAGE_UKRAIAN"
    const val BUNDLE_ANALYTICS_LANGUAGE_ABRIC = "LANGUAGE_ABRIC"
    const val BUNDLE_ANALYTICS_LANGUAGE_TURKEY = "LANGUAGE_TURKEY"

    const val SETTING_RADIO_CLICK_FIRST = "SETTING_RADIO_CLICK_FIRST"
    const val SETTING_RADIO_CLICK_AGAIN = "SETTING_RADIO_CLICK_AGAIN"
    const val SETTING_FEEDBACK_FIRST = "SETTING_FEEDBACK_FIRST"
    const val SETTING_FEEDBACK_AGAIN = "SETTING_FEEDBACK_AGAIN"
    const val SETTING_RATEUS_FIRST = "SETTING_RATEUS_FIRST"
    const val SETTING_RATEUS_AGAIN = "SETTING_RATEUS_AGAIN"
    const val SETTING_PRIVACY_FIRST = "SETTING_PRIVACY_FIRST"
    const val SETTING_PRIVACY_AGAIN = "SETTING_PRIVACY_AGAIN"
    const val SETTING_LANGUAGE_AGAIN = "SETTING_LANGUAGE_AGAIN"
    const val SETTING_LANGUAGE_FIRST = "SETTING_LANGUAGE_FIRST"

    const val EXPIRED = "res_expired"

    object PreferencesKey {

        const val IS_FIRST_OPEN = "IS_FIRST_OPEN"
        const val LANG_CODE = "LANG_CODE"
        const val FLASH_SPEED = "FLASH_SPEED"
        const val VOICE_LOCAL = "VOICE_LOCAL"

        const val IS_FIRST_RADIO_SETTING = "IS_FIRST_RADIO_SETTING"
        const val IS_FIRST_FEEDBACK_SETTING = "IS_FIRST_FEEDBACK_SETTING"
        const val IS_FIRST_RATEUS_SETTING = "IS_FIRST_RATEUS_SETTING"
        const val IS_FIRST_PRIVACY_SETTING = "IS_FIRST_PRIVACY_SETTING"
        const val IS_FIRST_LANGUAGE_SETTING = "IS_FIRST_LANGUAGE_SETTING"

        const val IS_FIRST_INSTALL = "is_first_install"
        const val IS_FIRST_OPEN_INTRO_1 = "is_first_open_intro_1"
        const val IS_FIRST_OPEN_INTRO_2 = "is_first_open_intro_2"
        const val IS_FIRST_OPEN_INTRO_3 = "is_first_open_intro_3"
        const val IS_FIRST_OPEN_LANGUAGE = "is_first_open_language"
        const val FIRST_TIME_OPEN_APP = "FIRST_TIME_OPEN_APP"

        const val IS_FIRST_OPEN_SETTING = "IS_FIRST_OPEN_SETTING"

        const val LANGUAGE_SCROLL_POSITION = "LANGUAGE_SCROLL_POSITION"
    }

}